version: 2.1
jobs:
  SourceGuard:
    docker: 
      - image: sourceguard/sourceguard-cli:latest
    steps:
      - checkout # check out source code to working directory
      - run: /sourceguard-cli --src ./

workflows:
  version: 2
  build_and_test:
    jobs:
      - SourceGuard